### PR TITLE
Close #269 move capture payment to job instead run instantly

### LINKED ISSUE #269: Payment hold & mark order to completed but capture payment fail which cause to failed

### PR DESCRIPTION
**Pull request by theachoem**
## Problem
- User make purchase & pay & in processing payment screen
- Our system, we:
  step 1. Check payment & mark payment as hold
  step 2. Process order & mark order complete
  step 3. Capture the payment
    In step 3, capture payment can have connection issue which cause the whole class to failed & refund to user. But when refund, order state still complete which cause problem.

## Solution
Once pass the step 2, which mean payment is hold & order is completed, we capture payment in job instead. So, If paymen.capture fail in the case such as a connection error to ABA, it will retry in sidekiq.

& User will get the ticket in that case (instead refund & keep order state still complete).

### CODE REVIEW

File: app/jobs/vpago/payment_capturer_job.rb [hunk 1]
```diff
@@ -0,0 +1,8 @@
+module Vpago
+  class PaymentCapturerJob < ::ApplicationUniqueJob
+    def perform(payment_id)
```
Comment (channainfo) [inline app/jobs/vpago/payment_capturer_job.rb:6]: Let's give this queue a name, for instance, **payment_processing** and give it higher priority in the Sidekiq config 

```
  - [payment_processing, 3]
  - default
  ...
```

If we can add a spec to test the queue name for this job as well.

**Review by channainfo — CHANGES_REQUESTED** [review]
